### ISSUE TITLE
panic: runtime error: invalid memory address or nil pointer dereference

### ISSUE THREAD

**Issue by ghost** [PurpleSec/Watcher#1]
I got this error when running bot first time. Please help

`
root@local # /opt/Watcher-1.4.1/bin/watcher -clear-all -f config.json
2023/04/19 15:03:37 [ INFO]: Twitter Watcher Telegram Bot Started, spinning up threads..
2023/04/19 15:03:37 [ INFO]: Starting Telegram receiver thread..
2023/04/19 15:03:37 [ INFO]: Starting Telegram sender thread..
2023/04/19 15:03:38 [ INFO]: Starting Twitter stream thread..
2023/04/19 15:03:38 [ INFO]: Starting Twitter ID mapping resolve task..
2023/04/19 15:03:38 [ INFO]: Twitter watch list is empty, not starting Twitter stream..
2023/04/19 15:08:12 [ INFO]: Attempting to reload Twitter stream..
2023/04/19 15:08:12 [ INFO]: Starting Twitter ID mapping resolve task..
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x0 pc=0x6973b1]

goroutine 26 [running]:
github.com/PurpleSec/watcher.(*Watcher).resolve(0xc000182000, {0x7ad7d0, 0xc000180050}, 0xc00019fea8?, 0x0)
        github.com/PurpleSec/watcher/twitter.go:126 +0x1b11
github.com/PurpleSec/watcher.(*Watcher).stream(0xc000182000, {0x7ad7d0, 0xc000180050}, 0x0?, 0x0?, 0x0?)
        github.com/PurpleSec/watcher/twitter.go:320 +0x56
github.com/PurpleSec/watcher.(*Watcher).watch(0xc000182000, {0x7ad7d0, 0xc000180050}, 0x0?, 0xc0001560a0, 0x0?)
        github.com/PurpleSec/watcher/twitter.go:264 +0x1310
created by github.com/PurpleSec/watcher.(*Watcher).Run
        github.com/PurpleSec/watcher/watcher.go:79 +0x38a
`

OS: Ubuntu 22.04
Watcher version: 1.4.1 
Golang version: go1.20.3 linux/amd64
Mariadb  version: 15.1 Distrib 10.6.12-MariaDB, for debian-linux-gnu (x86_64) using  EditLine wrapper
Upx version: 3.96

**Comment by iDigitalFlame** [comment]
Hello, thanks for the issue report!
It seems like a user lookup returned a nil user while processing a UserLookupRequest.
I've added a commit for some nil checks in that section (I didn't know one of those could have failed after the first one).

Try the updated version from master and if that fixes the issue, I'll push it into a new version.
Thanks!

**Comment by ghost** [comment]
It work, thanks.

**Comment by iDigitalFlame** [comment]
Awesome! Thanks, I'll push it to a release!
